name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Run tests
      run: |
        cd frontend
        npm run lint
        npx vue-tsc --noEmit
        
    - name: Build for production
      run: |
        cd frontend
        npm run build
        
    - name: Create changelog
      id: changelog
      run: |
        # Generate changelog from git commits
        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s (%h)" >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
    - name: Create Release Archive
      run: |
        tar -czf osint-framework-${{ github.ref_name }}.tar.gz -C dist .
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: OSINT Framework ${{ github.ref_name }}
        body: |
          ## 🚀 What's New in ${{ github.ref_name }}
          
          ${{ env.CHANGELOG }}
          
          ## 📦 Installation
          
          ### Option 1: Download Release
          Download the `osint-framework-${{ github.ref_name }}.tar.gz` file and extract it to a web server.
          
          ### Option 2: Clone Repository
          ```bash
          git clone https://github.com/${{ github.repository }}.git
          cd OSINT-Framework
          npm install:all
          npm run build
          ```
          
          ### Option 3: Use GitHub Pages
          Visit the live version at: https://${{ github.repository_owner }}.github.io/OSINT-Framework
          
          ## 🔧 Development
          
          ```bash
          git clone https://github.com/${{ github.repository }}.git
          cd OSINT-Framework
          npm install:all
          npm run dev
          ```
          
          ## 📋 Full Changelog
          **Full Changelog**: https://github.com/${{ github.repository }}/compare/v2.0.0...${{ github.ref_name }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./osint-framework-${{ github.ref_name }}.tar.gz
        asset_name: osint-framework-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        tag_name: ${{ github.ref_name }}
        tag_message: 'Release ${{ github.ref_name }}'
